package com.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-05T09:40:11.161-04:00
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "wsEstablishmentsHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WsEstablishmentsHttpPost {

    @WebResult(name = "ArrayOfOBJ_Establishment", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod
    public ArrayOfOBJEstablishment getEstablishments(
        @WebParam(partName = "status", name = "status", targetNamespace = "http://tempuri.org/")
        java.lang.String status,
        @WebParam(partName = "establishment", name = "establishment", targetNamespace = "http://tempuri.org/")
        java.lang.String establishment,
        @WebParam(partName = "municipality", name = "municipality", targetNamespace = "http://tempuri.org/")
        java.lang.String municipality
    );
}
