
package com.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-05T09:40:11.126-04:00
 * Generated source version: 2.6.8
 * 
 */
public final class WsEstablishmentsSoap_WsEstablishmentsSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "wsEstablishments");

    private WsEstablishmentsSoap_WsEstablishmentsSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsEstablishments.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsEstablishments ss = new WsEstablishments(wsdlURL, SERVICE_NAME);
        WsEstablishmentsSoap port = ss.getWsEstablishmentsSoap();  
        
        {
        System.out.println("Invoking getEstablishments...");
        java.lang.String _getEstablishments_status = "";
        java.lang.String _getEstablishments_establishment = "";
        java.lang.String _getEstablishments_municipality = "";
        com.services.ArrayOfOBJEstablishment _getEstablishments__return = port.getEstablishments(_getEstablishments_status, _getEstablishments_establishment, _getEstablishments_municipality);
        System.out.println("getEstablishments.result=" + _getEstablishments__return);


        }

        System.exit(0);
    }

}
