package com.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-05T09:40:11.175-04:00
 * Generated source version: 2.6.8
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "wsEstablishmentsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEstablishmentsSoap {

    @WebResult(name = "getEstablishmentsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getEstablishments", targetNamespace = "http://tempuri.org/", className = "com.services.GetEstablishments")
    @WebMethod(action = "http://tempuri.org/getEstablishments")
    @ResponseWrapper(localName = "getEstablishmentsResponse", targetNamespace = "http://tempuri.org/", className = "com.services.GetEstablishmentsResponse")
    public com.services.ArrayOfOBJEstablishment getEstablishments(
        @WebParam(name = "status", targetNamespace = "http://tempuri.org/")
        java.lang.String status,
        @WebParam(name = "establishment", targetNamespace = "http://tempuri.org/")
        java.lang.String establishment,
        @WebParam(name = "municipality", targetNamespace = "http://tempuri.org/")
        java.lang.String municipality
    );
}
